# Generated by Django 4.2.19 on 2025-04-19 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contactEmail', models.CharField(max_length=255)),
                ('contactPhone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=1)),
                ('currentBalance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('customerName', models.CharField(max_length=255)),
                ('addressText', models.CharField(max_length=255)),
                ('addressLongitude', models.FloatField(blank=True, null=True)),
                ('addressLatitude', models.FloatField(blank=True, null=True)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=255)),
                ('balanceAfter', models.FloatField()),
                ('cardNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.order')),
                ('transactionStatus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('isStaff', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('failedLoginAttempts', models.PositiveIntegerField(default=0)),
                ('lastFailedLogin', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldChanged', models.CharField(max_length=255)),
                ('oldValue', models.CharField(max_length=255)),
                ('newValue', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.status'),
        ),
    ]
