# Generated by Django 4.2.19 on 2025-04-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_isactive_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderAssignments',
            field=models.ManyToManyField(through='Api.OrderAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
