# Generated by Django 4.2.19 on 2025-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('contactName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('businessType', models.CharField(max_length=255)),
                ('driversCount', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
