# Generated by Django 4.2.19 on 2025-04-29 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
