# Generated by Django 4.2.19 on 2025-04-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_contact_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='role',
            name='requiresMerchant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.merchant'),
        ),
    ]
